Rails.application.routes.draw do
  # resources -> used for any kind of CRUD 
  resources :portfolios
  #generated by default rails g controller Pages home about contact
  # get 'pages/home'
  # get 'pages/about'

  # mapping whith the controller before the # and then action 
  # the get 'something' can be customized as I want
  get 'about-me', to: 'pages#about'
  
  #get 'pages/contact'

  get 'contact', to: 'pages#contact'

  # resources -> reserved word -> encapsulates all the popular routes that the app use. -> restful routing -> means especific and standardized names for our routes -> resources contains all the routes
  resources :blogs
  
  # the root path
  root to: 'pages#home'
end
